### ISSUE TITLE
[Feature Request]: Panel data and individual effect control

### ISSUE THREAD

**Issue by zhangc927** [DoubleML/doubleml-for-py#194]
### Describe the feature you want to propose or implement

Thank you for your excellent work, which is very helpful for learning and using DML. I have a question I'd like your guidance on. If I apply DML to panel data, how can the individual fixed effects be controlled? Directly generate individual dummy variables? My current data has about 30,000 individuals, but only three years of data, it may not be appropriate to generate individual dummy variables. But I don't know how to control for imperceptible individual fixed effects. thank you again！

**Comment by SvenKlaassen** [comment]
Thank you for your suggestion.
Could you use first differences (or similar transformations) to remove individual fixed effects?

For panel data, we are currently working on an implementation of a difference-in-differences estimation based on double machine learning (see e.g. [Zimmert (2018)](https://arxiv.org/abs/1809.01643) or [Chang (2020)](https://academic.oup.com/ectj/article/23/2/177/5722119)), but this may take a while until the estimators are available on the main branch (currently on branch https://github.com/DoubleML/doubleml-for-py/tree/s-did)

**Comment by zhangc927** [comment]
Thank you for your advice. That's exactly what I did

**Comment by SvenKlaassen** [comment]
I will close this, since we have added DID models in #145 .

**Comment by simonschoe** [comment]
@SvenKlaassen
Hi Sven, naive question: If i employ first differences (i.e., demeaning all variables based on the fixed effects), I'll have an issue with cross-fitting right? That is, if I demean prior to cross-fitting, the folds are not independent from each other, because observations in one fold might have been demeaned using information encoded in observations from another fold. How do I handle this issue? Is this where the DiD estimator comes into play?

**Comment by SvenKlaassen** [comment]
Hi @simonschoe,

thanks for your question. That would be true. Currently, we only consider two time periods in the DiD model (and only first difference on the outcome not demeaning). 
So either one considers each time period seperately or one has to impose more structure (e.g. linearity) on the problem. Depending on your model clustering (ensuring correct cross-fitting) might be helpful.

**Comment by simonschoe** [comment]
Thanks for your reply! In my setting, I am working with unit (firm) and time (year) fixed effects. I cannot see a clear way to keep these fixed effects while adhering to cross-fitting best practices (i.e., avoiding data leakage). That is, considering time periods separately is infeasible (it would drastically reduce the sample per year and not solve the issue in terms of unit-level fixed effects). What do you exactly mean by saying:
> one has to impose more structure (e.g. linearity) on the problem.

**Comment by SvenKlaassen** [comment]
Regarding the cross-fitting:
Using two-way clustering (see [Example](https://docs.doubleml.org/stable/examples/py_double_ml_multiway_cluster.html)) with respect to unit and time would ensure that the cross-fitting never uses the same unit or time variable for training and testing at the same time (still this might pose problems if you have too few observations in each period).

The unit level fixed effect would be vanishing if you only consider the differenced outcomes

$$Y_{it} - Y_{it-1},$$

but as you said this would not solve your small sample problem.

I am not an expert on panel data, but I suppose for multiple periods the final estimate should be quite dependend on your model (or your choice of estimate would implicitly assumes a specific structure). E.g. linear panel models are very helpful, because you have to assume some type of time-invariant structure on your covariates.
